### ISSUE TITLE
Paths wrong repositioning 

### ISSUE THREAD

**Issue by mRmEEeZ** [zHaytam/Blazor.Diagrams#28] opened 2020-10-09 23:10 UTC
Hello,

first of all I want to thank you for this amazing and stunning library 👍 

I found this issue when I resize, zooming and going away then return back to the nodes

![Capture](https://user-images.githubusercontent.com/57133128/95638550-b81d4000-0a9d-11eb-9197-da1029d9d513.PNG)

library version : 1.0.4
Blazor-Wasm

**Comment by zHaytam** [comment] 2020-10-09 23:12
I'm not sure I 100% get it. Is it possible for you to record a GIF that shows how you got the problem please?  
In the meantime, I'll check on my end to see if I can reproduce it.

**Comment by mRmEEeZ** [comment] 2020-10-09 23:34
![issue](https://user-images.githubusercontent.com/57133128/95639424-0ed84900-0aa1-11eb-835a-127c3ec92b8c.gif)

**Comment by zHaytam** [comment] 2020-10-10 09:16
There is indeed a bug in the following actions:
1. Hide nodes
2. Zoom in or out
3. Reshow nodes

I will fix this asap!

**Comment by mRmEEeZ** [comment] 2020-10-10 19:18
btw , is there anyway to put label over the arrow ? and arrow curved would be nice along side with curved lines too
also coloring links is good too

thanks

**Comment by zHaytam** [comment] 2020-10-10 19:21
I created a seperate issue for this. For the labels over the arrow they are gonna come but not right now unfortunately as it needs a bit of work, for the other two suggestions they are on my todo list so they will be coming soon.

**Comment by mRmEEeZ** [comment] 2020-10-10 19:23
awesome !
it is really one of the best libraries for blazor
i hope this project will become bigger and cover also "report designer" features ;)

cheers !

**Comment by zHaytam** [comment] 2020-10-11 15:24
Fixed in #30 
Version 1.0.4.1 was uploaded to NuGet!

If the issue is still there, feel free to re-open.

**Closed by zHaytam** 2020-10-11 15:24 UTC
